- name: Add posix storage domain
  ovirt_storage_domains:
      name: "{{ posix_storage['dr_' + dr_target_host + '_name'] }}"
      critical_space_action_blocker: "{{ posix_storage['dr_critical_space_action_blocker'] }}"
      warning_low_space: "{{ posix_storage['dr_warning_low_space'] }}"
      wipe_after_delete: "{{ posix_storage['dr_wipe_after_delete'] }}"
      backup: "{{ posix_storage['dr_backup'] }}"
      host: "{{ ovirt_hosts[0].name }}"
      data_center: "{{ posix_storage['dr_' + dr_target_host + '_dc_name'] }}"
      auth: "{{ ovirt_auth }}"
      posixfs:
          path: "{{ posix_storage['dr_' + dr_target_host + '_path'] }}"
          address: "{{ posix_storage['dr_' + dr_target_host + '_address'] }}"

- name: Append to succeed_storage_domains
  set_fact:
    succeed_storage_domains: "{{ succeed_storage_domains }} + [ \"{{ posix_storage['dr_' + dr_target_host + '_name'] }}\" ]"
  when: result | succeeded

- name: Append to failed_storage_domains
  set_fact:
    failed_storage_domains: "{{ failed_storage_domains }} + [ \"{{ posix_storage['dr_' + dr_target_host + '_name'] }}\" ]"
  when: result | failed