- name: Fetch unregistered VMs from storage domain
  ovirt_storage_vms_facts:
      nested_attributes: "id"
      unregistered: True
      storage_domain: "{{ storage.name }}"
      auth: "{{ ovirt_auth }}"

- name: Set unregistered VMs
  set_fact:
      unreg_vms: "{{ unreg_vms|default([]) }} + {{ ovirt_storage_vms }}"

# TODO: We should filter out vms which were already exists in the setup (diskless VMs)
- include: tasks/recover/register_vm.yml
  with_items: "{{ ovirt_storage_vms }}"
  # We use loop_control so storage.name will not be overriden by the nested loop.
  loop_control:
     loop_var: unreg_vm
